### ISSUE TITLE
@functor needs better documentation

### ISSUE THREAD

**Issue by freemin7** [FluxML/Functors.jl#29]
I was studying the Flux source code how to create me own layer types.
I came across the macro `@functor` whose purpose remained unclear to me. After asking in Slack it was signaled to me that those question comes up a lot and that it should be answered here.

I could imagine the documentation taking these forms:

- Make really good clear examples and explanation of `@functor`  in docs and explain when you need it and what for
- an expansion of the affine tutorial which includes `@functor` as opposed to functor being out of context and vague at the end of the page. The tutorial should enable the user to develop a first-class flux layer.

**Comment by CarloLucibello** [comment]
the documentation has improved a lot since then. open a new issue if something is still amiss
