### ISSUE TITLE
Does `functor` have the  right semantics for Flux?

### ISSUE THREAD

**Issue by CarloLucibello** [FluxML/Functors.jl#49]
Due to the default fallback 
```julia
functor(T, x) = (), _ -> x
```
in [Functors.jl](https://github.com/FluxML/Functors.jl/blob/ccdc06355c7f7c1a96bc0e9e69110936c979cc0f/src/functor.jl#L1), every custom type is considered a leaf (i.e. it has no children) and we have to sprinkle `@functor MyType` everywhere in Flux and in user code. 
We could remove all this boilerplate by having by default what `@functor MyType` currently does. Then 99% of people could live their life completely unaware of `@functor/functor` (historically poorly documented and poorly understood) and only use the much clearer `trainable(x::MyType)` in case they need to customize the parameter collection.

Besides the transition, which I think could be made rather smooth, does anyone see any counterindication in changing the default?

**Comment by CarloLucibello** [comment]
@mcabbott @darsnack and I are generally in favor of this, although it should be carefully tested before release. @ToucheSir?

**Comment by mcabbott** [comment]
Structured arrays do seem like a concern, as #33 required a hand-written inverse, impossible for some types. We could easily exclude them from a traverse-anything scheme.
