### ISSUE TITLE
empty namedtuple is not a leaf

### ISSUE THREAD

**Issue by CarloLucibello** [FluxML/Functors.jl#52]
```julia
julia> Functors.isleaf((;))
false
```
I guess we should consider this a bug.

**Comment by ToucheSir** [comment]
Discussion about this was in https://github.com/FluxML/Functors.jl/pull/36#issuecomment-1314635373. Can you see any scenarios where having this be true would be helpful?

**Comment by ToucheSir** [comment]
The problem with using `isempty` is that `children([]) == true`. If anything, we would want to choose a type that has fewer methods defined and thus won't accidentally show up as a non-leaf. `Nothing` comes to mind, but if that's too generic than a custom `NoChildren` singleton type could work as well.

**Comment by CarloLucibello** [comment]
Assuming we want to stop specialcasing the empty tuple for `isleaf`, maybe better use a custom singleton rather than `nothing` so that we can make it (trivially) mappable.

**Comment by CarloLucibello** [comment]
before tagging v0.5 we should take a decision on this issue

**Comment by CarloLucibello** [comment]
Since no one actually complained about this, we can just keep things as they are.
